/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    FundRanking: typeof import('./src/components/market/FundRanking.vue')['default']
    FundSearch: typeof import('./src/components/FundSearch.vue')['default']
    IndexCard: typeof import('./src/components/market/IndexCard.vue')['default']
    MarketSection: typeof import('./src/components/market/MarketSection.vue')['default']
    MarketSidebar: typeof import('./src/components/market/MarketSidebar.vue')['default']
    PredictionCard: typeof import('./src/components/PredictionCard.vue')['default']
    PredictionChart: typeof import('./src/components/PredictionChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WatchlistAdd: typeof import('./src/components/watchlist/WatchlistAdd.vue')['default']
    WatchlistEmpty: typeof import('./src/components/watchlist/WatchlistEmpty.vue')['default']
  }
}
